const constants = {
    APISTATUS: "APISTATUS",

    //organization
    GET_ORGANIZATION_DETAILS: "GET_ORGANIZATION_DETAILS",
    EDIT_ORGANIZATION_DETAILS: "EDIT_ORGANIZATION_DETAILS",
    ADD_ORGANIZATION_MEMBER: "ADD_ORGANIZATION_MEMBER",
    

    //project
    GET_PROJECT_LIST: "GET_PROJECT_LIST",
    CREATE_NEW_PROJECT: "CREATE_NEW_PROJECT",
    GET_PROJECT_DETAILS: "GET_PROJECT_DETAILS",
    EDIT_PROJECT_DETAILS: "EDIT_PROJECT_DETAILS",
    ARCHIVE_PROJECT: "ARCHIVE_PROJECT",
    GET_PROJECT_VIDEOS: "GET_PROJECT_VIDEOS",
    REMOVE_PROJECT_MEMBER: "REMOVE_PROJECT_MEMBER",
    GET_PROJECT_MEMBERS: "GET_PROJECT_MEMBERS",
    GET_LANGUAGES: "GET_LANGUAGES",
    CREATE_NEW_VIDEO: "CREATE_NEW_VIDEO",
    COMPARE_TRANSCRIPTION_SOURCE: "COMPARE_TRANSCRIPTION_SOURCE",
    CLEAR_COMPARISON_TABLE:"CLEAR_COMPARISON_TABLE",
    COMPARISION_TABLE:"COMPARISION_TABLE",
    GET_PRIORITY_TYPES:"GET_PRIORITY_TYPES",
    DELETE_TASk:"DELETE_TASk",
    GET_VIDEO_TASK_LIST:"GET_VIDEO_TASK_LIST",
    GET_MANAGER_NAME:"GET_MANAGER_NAME",
    DELETE_Project:"DELETE_Project",
    ADD_PROJECT_MEMBERS:"ADD_PROJECT_MEMBERS",
    EXPORT_TRANSCRIPTION:"EXPORT_TRANSCRIPTION",
    DELETE_VIDEO:"DELETE_VIDEO",
    
    //User
    GET_USER_LIST: "GET_USER_LIST",
    GET_LOGGEDIN_USER_DETAILS: "GET_LOGGEDIN_USER_DETAILS",
    UPDATE_EMAIL: "UPDATE_EMAIL",
    UPDATE_PROFILE: "UPDATE_PROFILE",
    VERIFY_UPDATE_EMAIL: "VERIFY_UPDATE_EMAIL",
    GET_USER_DETAILS: "GET_USER_DETAILS",
    GET_USER_ACCESS_TOKEN: "GET_USER_ACCESS_TOKEN",

    //Task
    CREATE_NEW_TASk: "CREATE_NEW_TASk",
    GET_TASK_LIST: "GET_TASK_LIST",
    GET_TASK_DETAILS: "GET_TASK_DETAILS",
    GET_TRANSCRIPT_TYPES: "GET_TRANSCRIPT_TYPES",
    GET_VIDEO_DETAILS: "GET_VIDEO_DETAILS",
    GET_TASK_TYPE: "GET_TASK_TYPE",
    GET_ALLOWED_TASK: "GET_ALLOWED_TASK",
    GET_SUPPORTED_LANGUAGES: "GET_SUPPORTED_LANGUAGES",
    GET_TRANSCRIPT_PAYLOAD: "GET_TRANSCRIPT_PAYLOAD",
    SAVE_TRANSCRIPT: "SAVE_TRANSCRIPT",
};

export default constants;