const constants = {
    APISTATUS: "APISTATUS",

    //organization
    GET_ORGANIZATION_DETAILS: "GET_ORGANIZATION_DETAILS",
    EDIT_ORGANIZATION_DETAILS: "EDIT_ORGANIZATION_DETAILS",
    ADD_ORGANIZATION_MEMBER: "ADD_ORGANIZATION_MEMBER",
    

    //project
    GET_PROJECT_LIST: "GET_PROJECT_LIST",
    CREATE_NEW_PROJECT: "CREATE_NEW_PROJECT",
    GET_PROJECT_DETAILS: "GET_PROJECT_DETAILS",
    EDIT_PROJECT_DETAILS: "EDIT_PROJECT_DETAILS",
    ARCHIVE_PROJECT: "ARCHIVE_PROJECT",
    GET_PROJECT_VIDEOS: "GET_PROJECT_VIDEOS",
    REMOVE_PROJECT_MEMBER: "REMOVE_PROJECT_MEMBER",
    GET_PROJECT_MEMBERS: "GET_PROJECT_MEMBERS",
    GET_LANGUAGES: "GET_LANGUAGES",
    CREATE_NEW_VIDEO: "CREATE_NEW_VIDEO",
    COMPARE_TRANSCRIPTION_SOURCE: "COMPARE_TRANSCRIPTION_SOURCE",
    COMPARISION_TABLE:"COMPARISION_TABLE",
    
    //User
    GET_USER_LIST: "GET_USER_LIST",
    GET_LOGGEDIN_USER_DETAILS: "GET_LOGGEDIN_USER_DETAILS",
    UPDATE_EMAIL: "UPDATE_EMAIL",
    UPDATE_PROFILE: "UPDATE_PROFILE",
    VERIFY_UPDATE_EMAIL: "VERIFY_UPDATE_EMAIL",
    GET_USER_DETAILS: "GET_USER_DETAILS",

    //Task
    CREATE_NEW_TASk: "CREATE_NEW_TASk",
    GET_TASK_LIST: "GET_TASK_LIST",
    GET_TASK_DETAILS: "GET_TASK_DETAILS",
};

export default constants;